- name: GitHub Pull Request Action
  uses: repo-sync/pull-request@v2.6.1

on:
  push:
    branches:
    - release/prod

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "release/dev"
        github_token: ${{ secrets.GITHUB_TOKEN }}
